redirection

diff --git a/web_server/3-redirection b/web_server/3-redirection
--- a/web_server/3-redirection
+++ b/web_server/3-redirection
@@ -36,9 +36,17 @@ SERVER_CONFIG="server {
 # Write the configuration to the default server block
 bash -c "echo -e '$SERVER_CONFIG' > /etc/nginx/sites-available/default"
 
-# Check if Nginx is running and start or restart it accordingly
-if [ "$(pgrep -c nginx)" -le 0 ]; then
-  service nginx start
+# Create a symbolic link to the sites-enabled directory
+sudo ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
+
+# Test Nginx configuration for syntax errors
+sudo nginx -t
+
+# If the config is correct, restart Nginx to apply the changes
+if [ $? -eq 0 ]; then
+  # Restart Nginx to apply the configuration changes
+  sudo service nginx restart
 else
-  service nginx restart
+  echo "Nginx configuration test failed!"
+  exit 1
 fi
